### ISSUE TITLE
NameError: name 'centrality' is not defined

### ISSUE THREAD

**Issue by Michael98Liu** [Didayolo/ranky#5]
Thanks for the amazing package! However, I encountered an error: When I invoke `rk.evolution_strategy()` i encounter the given NameError.

Is it because, in `ranking.py`, you did not import `centrality` from `metric.py`?

**Comment by Didayolo** [comment]
Hi, thank you for reporting this issue. I'll look into it.

**Comment by Didayolo** [comment]
@Michael98Liu 

It should be fixed by my [last commit](https://github.com/Didayolo/ranky/commit/70a952e44db348fbbd1183e045a908e2fc41928a) ([v0.3.0](https://pypi.org/project/ranky/)).

Feel free to give an update if you are facing any problem. Also, I haven't been using the evolution strategy in a while and I'm curious about how it performs.
